Add WebSocketChannel.`ready` field and IOWebSocketChannel factory `connectTimeout` parameter
dart-lang/web_socket_channel pull request #240
Opened 2022-12-07 09:27 UTC by iota9star

continue #60 and #85

2022-12-21 02:09 UTC, brianquinlan requested changes
Really nice change! There are some test failures:
https://github.com/dart-lang/web_socket_channel/actions/runs/3637557082/jobs/6359843414

I also had a few small comments about the code.

Finally, let's get a quick sanity check from @kevmoo when the above 2 things are addressed.

Thanks again!

2022-12-21 02:09 UTC, brianquinlan commented on test/io_test.dart
> +    expect(channel.ready, doesNotComplete);
Could you check that `channel.ready` raises `TimeoutException` (or whatever the actual exception type is).

2022-12-21 02:09 UTC, brianquinlan commented on lib/html.dart
> +  /// Future indicating if the connection has been established.
I think that you don't normally document overrides.

2022-12-21 02:09 UTC, brianquinlan commented on lib/io.dart
> +  /// Future indicating if the connection has been established.
I think that you don't normally document overrides.

2022-12-21 19:42 UTC, brianquinlan commented on lib/html.dart
>        innerWebSocket.onOpen.first.then((_) {
If `innerWebSocket.readyState == WebSocket.CONNECTING` then won't you call both:
`_readyCompleter.completeError(...)` and
`_readyCompleter.complete();`

2022-12-21 19:42 UTC, brianquinlan commented on test/io_test.dart
> +      await channel.ready;
Can this be written as:

expect(() async => await channel.ready, throwsA(TimeoutException));

?

2022-12-22 02:06 UTC, iota9star commented on lib/html.dart
>        innerWebSocket.onOpen.first.then((_) {
If `innerWebSocket.readyState == WebSocket.CONNECTING`, it will call one of them between [`onError`](https://github.com/iota9star/web_socket_channel/blob/a479f0675cfb9b010bb2e04ef1dd9a681baf4f92/lib/html.dart#L100-L105) and [`onOpen`](https://github.com/iota9star/web_socket_channel/blob/a479f0675cfb9b010bb2e04ef1dd9a681baf4f92/lib/html.dart#L92-L96). Two related tests ([test1](https://github.com/iota9star/web_socket_channel/blob/a479f0675cfb9b010bb2e04ef1dd9a681baf4f92/test/html_test.dart#L75-L83) [test2](https://github.com/iota9star/web_socket_channel/blob/a479f0675cfb9b010bb2e04ef1dd9a681baf4f92/test/html_test.dart#L141-L164)) cover this situation

2022-12-22 02:28 UTC, brianquinlan commented on lib/html.dart
>        innerWebSocket.onOpen.first.then((_) {
Oops, I meant if `innerWebSocket.readyState != WebSocket.CONNECTING`.

I'm basically asking if:
```dart
      innerWebSocket.onOpen.first.then((_) {
         ....
```

should be executed if `innerWebSocket.readyState != WebSocket.CONNECTING`.

2022-12-22 02:58 UTC, iota9star commented on lib/html.dart
>        innerWebSocket.onOpen.first.then((_) {
If `innerWebSocket.readyState == WebSocket.CLOSING || innerWebSocket.readyState == WebSocket.CLOSED`, `onError` and `onOpen` will not be called

2022-12-22 03:03 UTC, iota9star commented on lib/html.dart
>        innerWebSocket.onOpen.first.then((_) {
I changed the condition, which can better help others understand. b69ec9ee97af7232426b0f4520b51342119bd2fe

2022-12-22 20:17 UTC, brianquinlan reviewed
I'm going to ask for a quick review from someone more familiar with this pacakge.

2022-12-22 20:50 UTC, kevmoo reviewed
Notes on the version, but if technically it seems fine LGTM

2022-12-22 20:50 UTC, kevmoo commented on CHANGELOG.md
> +- Added a Future `ready` property to `WebSocketChannel`, which completes when
If we're adding properties we should do 2.3.0

2022-12-22 20:50 UTC, kevmoo commented on CHANGELOG.md
> +- Added a `connectTimeout` parameter to the `IOWebSocketChannel.connect` factory,
ditto

2022-12-23 02:08 UTC, brianquinlan reviewed
Could you update pubspec.yaml to indicate your new version?

That seems to be previous practice:
https://github.com/dart-lang/web_socket_channel/commit/4b46c0c4196a5e76c2b0e2589ed37de247d35938

2022-12-23 02:23 UTC, merged

2023-01-10 01:30 UTC, ycherniavskyi commented
@brianquinlan, is it possible [to publish](https://pub.dev) the package version 2.3.0 with these changes?

2023-01-10 02:25 UTC, brianquinlan commented
@natebosch is working on it - we wanted wait until after the holidays in case something went wrong.

2023-01-11 17:45 UTC, brianquinlan commented
I just published 2.3.0