Allow pkg:web v0.3.0
dart-lang/web_socket_channel pull request #306
Opened 2023-12-19 17:54 UTC by NotTsunami

Closes #305

2023-12-19 21:28 UTC, NotTsunami commented
The [exact same issue](https://github.com/dart-lang/http/issues/1052) was observed on the http side. Mimic the [same fix](https://github.com/dart-lang/http/commit/c125ed5423a864dfb9057b6b19d3dfed1d0266e6) for http. The range should probably be fine.

2023-12-19 23:40 UTC, kevmoo requested changes

2023-12-19 23:40 UTC, kevmoo commented on pubspec.yaml
> +  web: '>=0.3.0 <0.5.0'
please bump the version to `2.4.2` and add an entry to the chaneglog.

Thanks!

2024-01-04 16:27 UTC, NotTsunami commented
Missed the comment before going on vacation, my apologies. Made the changes online, let me know if you need a squash.

2024-01-04 17:38 UTC, kevmoo approved these changes

2024-01-04 17:39 UTC, merged